sudo: required
services:
    - docker
    
before_install:
    - docker build -t mritunjayonemail/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run mritunjayonemail/react-test npm test -- --coverage

after_success:
    - docker build - t mritunjayonemail/multi-client ./client
    - docker build - t mritunjayonemail/multi-nginx ./nginx
    - docker build - t mritunjayonemail/multi-server ./server
    - docker build - t mritunjayonemail/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push mritunjayonemail/multi-client 
    - docker push mritunjayonemail/multi-nginx
    - docker push mritunjayonemail/multi-server
    - docker push mritunjayonemail/multi-worker
    